// FILTER

const SET_FILTER = "SET_FILTER";
const CLEAR_FILTER = "CLEAR_FILTER";

// ROWS

const SET_ROWS = "SET_ROWS";
const ADD_ROW = "ADD_ROW";
const DELETE_ROW = "DELETE_ROW";
const UPDATE_ROW = "UPDATE_ROW";

// COLUMNS

const SET_COLUMNS = "SET_COLUMNS";

// SORT

const SET_SORT = "SET_SORT";
const CLEAR_SORT = "CLEAR_SORT";

// MODAL

const SET_MODAL = "SET_MODAL";
const UNSET_MODAL = "UNSET_MODAL";

// POPOVER

const SET_POPOVER = "SET_POPOVER";
const UNSET_POPOVER = "UNSET_POPOVER";

export {
  // FILTER
  SET_FILTER,
  CLEAR_FILTER,
  // ROWS
  SET_ROWS,
  ADD_ROW,
  DELETE_ROW,
  UPDATE_ROW,
  // COLUMNS
  SET_COLUMNS,
  // SORT
  SET_SORT,
  CLEAR_SORT,
  // MODAL
  SET_MODAL,
  UNSET_MODAL,
  // POPOVER
  SET_POPOVER,
  UNSET_POPOVER,
};
